### ISSUE TITLE
init_conc argument with `Replicate()` is redundant

### ISSUE THREAD

**Issue by jmrohwer** [EnzymeML/PyEnzyme#11]
The init method signature for the `Replicate()` class has an argument `init_conc`:

```python
class Replicate(EnzymeMLBase):

    def __init__(
        self,
        replica,
        reactant,
        type_,
        data_unit,
        time_unit,
        reaction=None,
        measurement="unspecified",
        init_conc="NONE",
        data=None,
        time=None,
        isCalculated=False,
        uri=None,
        creatorId=None
    ):
```
This is, however, redundant and should be removed in my opinion to avoid confusion.
- The `Measurement()` already has an assigned `initConc` via this argument of the `addData()` method. (Also note inconsistency of `initConc` vs. `init_conc`.)
- All replicates should have the same initial concentrations as the measurement, otherwise they would not be replicates. So this should only be specified once (in the Measurement).
- The `init_conc` entered via the `Replicate()` class is not stored in the XML, and this information is thus not round-trippable.

**Comment by JR-1991** [comment]
Thanks for pointing this out! Indeed the init_conc argument is redundant now regarding the addition of the new Measurement class. The argument and all corresponding methods were removed in commit e3732e6.
