### ISSUE TITLE
Initial concentration of Reactant not stored in XML if init_conc=0.0

### ISSUE THREAD

**Issue by jmrohwer** [EnzymeML/PyEnzyme#12]
When a new reactant is created with
```python
enzmldoc.addReactant(Reactant(
                    name = ...,
                    vessel = ...,
                    init_conc = 0.0,
                    substanceunits = ...,
                    ...
):
```
the initial concentration is not stored in the XML when the value is zero (the `init_conc` key is completely absent from the XML), it is however stored when the value is non zero.

This creates a problem for simulation tools (e.g. PySCeS) wanting to simulate the kinetic model, because the initial concentration is loaded as NaN instead of zero.

**Comment by JR-1991** [comment]
Thanks, the issue has been fixed in commit 173d93f7b1efb87d6700dcef28130001ed42a76b.
