### ISSUE TITLE
How to send in omex archives to enzymemL read

### ISSUE THREAD

**Issue by StephanM87** [EnzymeML/PyEnzyme#44]
I have trouble with sending in EnzymeMl documents:

If I send a enzymeml document, which was before generated by Pyenzmye with the following code:

```python
def test_request():
    files = {"omex_archieve":open("tests/enzml.omex", "rb")}

    req = requests.post("http://127.0.0.1:5000/read", files=files)
    
   print(req.text)

```

The request I get is :

```
{"detail":[{"loc":["body","omex_archive"],"msg":"field required","type":"value_error.missing"}]}
```

based on the documentation of the REST API, I have to send in the omex archieve as multiform/form-data correct?! 

![grafik](https://user-images.githubusercontent.com/48381090/168275222-9abdad3a-5280-4097-8f9b-17f7a3994607.png)

Do you have an idea, why the exception in called and what I'm doing wrong with the type?

**Comment by JR-1991** [comment]
Thanks for the issue Stephan! Looking at your code, the error may result from a typo - You spelled it `omex_archieve` when it should be `omex_archive`:

```python
# Correct
files = {"omex_archive":open("tests/enzml.omex", "rb")}
```

Also tested it with the following code and a random OMEX to verify on our official REST-API that runs the current Docker image:

```python
response = requests.post(
    "https://enzymeml.sloppy.zone/read",
    files={"omex_archive": open("Simulated.omex", "rb")}
).json()
```

Out:

```python
{'name': 'Simple_Menten',
 'level': 3,
 'version': 2,
 'creators': {},
 'vessels': {'v0': {'name': 'Tube',
   'volume': 10.0,
   'unit': 'ml',
   'constant': True,
   'meta_id': 'METAID_V0',
   'id': 'v0'}},
 'proteins': {'p0': {'name': 'Protein',
   'meta_id': 'METAID_P0',
   'id': 'p0',
   'vessel_id': 'v0',
   'init_conc': 100.0,
   'constant': True,
   'boundary': False,
[...]
```

**Comment by StephanM87** [comment]
@JR-1991, thank you! I think this solved a problem, and it works now with the example from It works with the example archive : https://github.com/EnzymeML/PyEnzyme/blob/main/examples/Basic%20example/My_Experiment.omex 

 Nevertheless, when I upload the omex archive which was generates with the **Pyenzyme REST-API**, I get a stauts code 200 but still the error:

`"AttributeError: BIOCHEMICAL_REACTION"`

I attached the omex archive as google drive link:

https://drive.google.com/file/d/1xdySm5CE9FmcrpV6fYtus4RTO1kqKxwF/view?usp=sharing

Could you help and check out if you can see what went wrong?
