### ISSUE TITLE
Can't read in data type "Conversion [%]" from template

### ISSUE THREAD

**Issue by benjaminhadzovic** [EnzymeML/PyEnzyme#49]
I have trouble reading in a template where the data type "Conversion [%]" is used. 

Code:
`enzmldoc = pe.EnzymeMLDocument.fromTemplate("Example.xlsm")`

Error:
`KeyError: 'Conversion [%]'`

Here is the example file:
[Example.xlsx](https://github.com/EnzymeML/PyEnzyme/files/8992446/Example.xlsx)

With my local installation of PyEnzyme the data type can be read in. Even though i haven't changed the code of the local install.

**Comment by JR-1991** [comment]
Thanks for the submission! Just tried it using the current `main` branch and I can't reproduce the error - The conversion is read correctly. Here is a Colab Notebook where it also works. 

https://colab.research.google.com/drive/1qA85P852fenb8LkNfb0igzu9ru9722Vy?usp=sharing

Could you specify where exactly you get the error? Can you check the PyEnzyme Version using `pyenzyme.__version__`?
