### ISSUE TITLE
use of branches here on git?

### ISSUE THREAD

**Issue by robertgiessmann** [EnzymeML/PyEnzyme#5]
Hi @JR-1991 , 

you showed the REST API today -- I was wondering whether it wouldn't be a better place to have it in a separate repository, rather than another branch here. I definitely didn't look in the branches list, not sure how others use github in the end. But maybe you could increase visibility by making it a repo?

Thanks and best!

**Comment by JR-1991** [comment]
Hi Robert,

thank you for your feedback! The initial thought was to integrate the REST-API into PyEnzyme as a functionality shipped with the software. Indeed, having a seperate repo would definitely makes sense and we'll discuss if that is something we'd consider when the development is finished.

Regarding the branches, its still under development and thus kept inside its own branch, but will definitely be pushed into the main.

All the best!
