### ISSUE TITLE
Enzyme ML spreadsheets should support 96 Well-plate design

### ISSUE THREAD

**Issue by Vanry7** [EnzymeML/PyEnzyme#59]
Many experiments are run in 96-WP, so having an excel worksheet to organise them would be great. 
See attached my first draft, mainly for general organisation idea.

[96WP- Endpoint-V0.1.1.xlsm.zip](https://github.com/EnzymeML/PyEnzyme/files/12159015/96WP-.Endpoint-V0.1.1.xlsm.zip)

**Comment by haeussma** [comment]
Hi @Vanry7, I looked into your draft and made some modifications. I think we should keep the template as clean as possible. It should only serve as a template to enter data. Thus, no calculations should be done within the spreadsheet.
I modified your "ReactantTemplate" and "ProteinTemplate" sheets. I think they should be hidden, yet be used in the background by a Visual Basic script. The script should then:
- Copy the "ReactantTemplate" sheet
- Change the sheet name to the respective reactant name
- Change the field A2 in the copied "ReactantTemplate" to the respective reactant name

Then, the initial concentration of each specified reactant can be specified in the respective"ReactantTemplate" in the familiar 96well format.

The same applies for different proteins.

**Comment by Vanry7** [comment]
Hi,
Following the previous discussion and meeting, here is an updated version of the notebook.

Major updates includes:

- complete redesign in term of color to adapt to color-blindness (using the Viridis -plasma color scale)
- Creation of a page "readme" containing a detailed list of how to use the plate. 
- Removal of superfluous data from tables
- creation of a macro that create a named sheet upon modifying the list of entries in the "reactants" or "proteins list", with appropriates safeguard.
- creation of a sheet "plate summary", that helps visualise the complete content of the plate in one place through a macro, making easier for the user to know what's has been filled.

The things left to do:

- discuss the content of the sheets "reaction" and "kinetics", and clean them according to the enzymeML file.
- test with a small range of user to identify weakpont
- adding all the "mouse-over" comment to help with the sheet filling


As a side note, creating another sheet dedicated to the meta-data of protein expression, that could then be linked to this one (adding for instance a column in "proteins", to fill-in the sheet nam
[EnzymeML template 96WP draft-0.1.4.xlsm.zip](https://github.com/EnzymeML/PyEnzyme/files/12273644/EnzymeML.template.96WP.draft-0.1.4.xlsm.zip)
e) would make the collection and storage of meta data truly complete.

**Comment by Vanry7** [comment]
Hi, 
Everything has been updated, both visually and in design to make it more reliable and user-friendly.

Find attached the finished file.

[EnzymeML template 96WP draft-0.2.2.xlsm.zip](https://github.com/EnzymeML/PyEnzyme/files/12368192/EnzymeML.template.96WP.draft-0.2.2.xlsm.zip)

**Comment by haeussma** [comment]
Just finished edited [EnzymeML template 96WP draft-0.2.4.xlsm.zip](https://github.com/EnzymeML/PyEnzyme/files/12409774/EnzymeML.template.96WP.draft-0.2.4.xlsm.zip). Added a sheet in which the initial pH can be specified for each well individually. Additionally, I reworked the 'Read Me' sheet and added instructions on how to fill in the spreadsheet and how to convert the spreadsheet to a valid EnzymeML document.

Furthermore, I wrote a parser function for the new spreadsheed template, which is used by the class method fromTemplate() of ```EnzymeMLDocument```.

**Comment by EgonHeuson** [comment]
Hello guys, 
Finally I found the time to work on this. This template is amazingly done! 
I just allowed myself to propose a v0.2.5, which corrects few bugs from v0.2.4 (mainly data validation issue leading to cells that users could not fill in). I also corrected the format of the units to make it compliant with international writing, and colored additional cells to be more compliant to the documentation on the first page.
Finally, I also added a conversion tool to allow people that get "plate shape" data out of their plate reader, to transform them in to the required list in the "Data" sheet (by the way column G1 to H12 were missing in sheet "Data"). And I finally added a graph generation tool to help the user to quickly visualize their results. 
Could you let me know (if) what else needs to be done on the sheet to make it readily compatible with the EnzymeMLDocument?
Congrats again for this amazing template! i'll use it to encode all the data from my test dataset and see how it goes.

[EnzymeML template 96WP draft-0.2.5.xlsm.zip](https://github.com/EnzymeML/PyEnzyme/files/12602173/EnzymeML.template.96WP.draft-0.2.5.xlsm.zip)

**Comment by EgonHeuson** [comment]
Hey! 
New 0.2.6 version with quick correction accorded to Max's request (temperature units and suppression of the "other" option in the possibilities).

[EnzymeML template 96WP draft-0.2.6.xlsm.zip](https://github.com/EnzymeML/PyEnzyme/files/12610467/EnzymeML.template.96WP.draft-0.2.6.xlsm.zip)

**Comment by haeussma** [comment]
Hey!
Looked at 0.2.6. I really like the conversion tool from plate "snapshots" to list data for each well! I cleaned up the sheet and added a description to the read me section. I also changed the color in ProteinTemplate and ChemicalTemplate, since some cells were randomly colored.
These changes are in [EnzymeML template 96WP draft-0.2.7.xlsm.zip](https://github.com/EnzymeML/PyEnzyme/files/12616182/EnzymeML.template.96WP.draft-0.2.7.xlsm.zip). In the next days, I will adjust the spreadsheet reader of pyenzyme to accommodate the changes. After writing tests, we can merge the new functionalities into main.

**Comment by EgonHeuson** [comment]
Great!! :-D

**Comment by Vanry7** [comment]
Hi !
Just got the time to look at the last updates, it looks really great ! 
I'll present it to my group during our next training school so we can start to tinker with it and get some return from users

**Comment by JR-1991** [comment]
Is this issue resolved by now? If so, happy to close it 😊

**Comment by haeussma** [comment]
We will solve the issue of efficient processing of MTP data  with [MTPHandler](https://github.com/FAIRChemistry/MTPHandler) - dedicated tool for processing mtp data

**Comment by EgonHeuson** [comment]
Just adding the last version we've made here
[EnzymeML template 96WP draft-0.2.24.xlsm.zip](https://github.com/user-attachments/files/17165016/EnzymeML.template.96WP.draft-0.2.24.xlsm.zip)
