### ISSUE TITLE
Dimensionless unit

### ISSUE THREAD

**Issue by jmrohwer** [EnzymeML/PyEnzyme#8]
Currently, when a new dimensionless unit is created, this matches on `abs`, `absorption` or `dimensionless`, but the `UnitDef` is created as `absorption`:
https://github.com/EnzymeML/PyEnzyme/blob/32011fc22ee36bece374dedd2a30454ff384eb77/pyenzyme/enzymeml/tools/unitcreator.py#L68-L80

I would suggest that this `UnitDef` is created as `dimensionless`, for the following reasons:
- "absorption" or "absorbance" as it is also called, is actually a quantity, not a unit (in fact it is a dimensionless quantity). We should not confuse quantity and unit, e.g. concentration is a quantity which can have a unit molar. Nevertheless, when absorption is recorded in an experiment, the user might want to indicate this with `abs` or `absorption`, so we can continue matching on that, but the UnitDef should have the generic `dimensionless` name.
- There are other dimensionless units, e.g. equilibrium constant (Keq) for a reversible reaction with an equal number of educts and products. Currently, when entering this in a kinetic model as "dimensionless", the unit gets assigned as `absorption`, which makes no sense at all.

**Comment by jmrohwer** [comment]
In my opinion removing it would be cleaner, as it is not a unit but a quantity. Given that the Replicate Type attribute can be used to convey (and store) the information, there is really not a need for an "absorbance" unit and it is potentially confusing, aside from the same information potentially being stored in two separate places (`Type` attribute vs `abs` unit).

**Comment by JR-1991** [comment]
I agree with you, we should remove any redundancy to avoid any confusion. The support for abs/absorbance as unit names was dropped in commit 4d71160. I also added an error message to display the supported prefixes and units, such that it is clear which are supported by PyEnzyme.
